-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th10 29, 2021 lúc 04:33 AM
-- Phiên bản máy phục vụ: 10.4.21-MariaDB
-- Phiên bản PHP: 7.3.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `examples`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `comment`
--

CREATE TABLE `comment` (
  `comment_id` int(11) NOT NULL,
  `product_id` varchar(11) NOT NULL,
  `uid` int(11) NOT NULL,
  `content` text CHARACTER SET utf16 COLLATE utf16_vietnamese_ci NOT NULL,
  `date` datetime NOT NULL,
  `uname` varchar(100) NOT NULL,
  `admin_reply` text CHARACTER SET utf16 COLLATE utf16_vietnamese_ci NOT NULL,
  `sao` int(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `comment`
--

INSERT INTO `comment` (`comment_id`, `product_id`, `uid`, `content`, `date`, `uname`, `admin_reply`, `sao`) VALUES
(19, 'ASM04', 0, 'good', '2021-11-28 13:17:38', 'long014756', '', 3),
(20, 'ASM02', 3, 'Tốt', '2021-11-28 15:45:04', 'tester', '', 3);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `orders`
--

CREATE TABLE `orders` (
  `order_id` varchar(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `order_list` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}',
  `order_state` varchar(11) CHARACTER SET ascii NOT NULL DEFAULT 'pending',
  `order_price` int(255) NOT NULL DEFAULT 0,
  `address` varchar(1000) CHARACTER SET utf32 COLLATE utf32_vietnamese_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `orders`
--

INSERT INTO `orders` (`order_id`, `user_id`, `order_list`, `order_state`, `order_price`, `address`) VALUES
('0', 4, '[{\"amount\":\"6\",\"id\":\"AP02\"}]', 'done', 2574000, '12334'),
('1', 4, '[{\"amount\":\"5\",\"id\":\"AP02\"}]', 'done', 2145000, '4654'),
('2', 3, '[{\"amount\":\"1\",\"id\":\"ASM02\"}]', 'verified', 999000, '1sdaasdas'),
('3', 0, '[{\"amount\":\"1\",\"id\":\"ASM04\"},{\"amount\":\"1\",\"id\":\"G02\"}]', 'done', 3298000, '123'),
('4', 0, '[{\"amount\":\"2\",\"id\":\"ASM05\"}]', 'verified', 1598000, 'aooa'),
('5', 4, '[{\"amount\":\"1\",\"id\":\"AP02\"},{\"amount\":\"1\",\"id\":\"K01\"},{\"amount\":\"1\",\"id\":\"K02\"},{\"amount\":\"1\",\"id\":\"K03\"}]', 'done', 11426000, 'sadsd'),
('6', 4, '[{\"amount\":\"2\",\"id\":\"AP02\"},{\"amount\":\"3\",\"id\":\"K01\"},{\"amount\":\"3\",\"id\":\"K03\"}]', 'done', 23352000, 'qsdas'),
('7', 4, '[{\"amount\":\"19\",\"id\":\"AP02\"}]', 'done', 8151000, 'asdasda'),
('8', 3, '[{\"amount\":\"3\",\"id\":\"ASM02\"}]', 'pending', 2997000, '');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `products`
--

CREATE TABLE `products` (
  `link` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `product_code` varchar(8) NOT NULL,
  `loai` varchar(20) NOT NULL,
  `tensanpham_viethoa` varchar(225) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL,
  `tensanpham_vietthuong` varchar(225) NOT NULL,
  `price` varchar(20) NOT NULL,
  `mota` varchar(1000) NOT NULL,
  `cachbaoquan` varchar(2000) NOT NULL,
  `xuatxu` varchar(225) NOT NULL,
  `img` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`img`)),
  `other_code` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `price_numberic` int(255) NOT NULL,
  `total_rate` int(11) NOT NULL DEFAULT 0,
  `avg_rating` decimal(9,1) NOT NULL DEFAULT 0.0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `products`
--

INSERT INTO `products` (`link`, `product_code`, `loai`, `tensanpham_viethoa`, `tensanpham_vietthuong`, `price`, `mota`, `cachbaoquan`, `xuatxu`, `img`, `other_code`, `price_numberic`, `total_rate`, `avg_rating`) VALUES
('/product/product.php?id=AP01', 'AP01', 'Áo phông', 'ÁO PHÔNG DÁNG BÓ CỔ CAO', 'Áo phông dáng bó cổ cao', '429.000 VN', 'Áo phông dáng bó, cổ cao, dài tay.', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Bangladesh.', '[\"/product/aophong/images/AP01_1.png\", \"/product/aophong/images/AP01_2.png\", \"/product/aophong/images/AP01_3.png\",\"/product/aophong/images/AP01_4.png\"]', '[\"AP02\", \"AP03\", \"AP04\"]', 429000, 0, '0.0'),
('/product/product.php?id=AP02', 'AP02', 'Áo phông ', 'ÁO PHÔNG HIỆU ỨNG BẠC MÀU\r\n', 'Áo phông hiệu ứng bạc màu', '429.000 VND', 'Áo phông bó sát, cổ tròn, dài tay. Do công nghệ nhuộm vải nên họa tiết trên mỗi sản phẩm là độc đáo và duy nhất và có thể có các chi tiết khác biệt so với ảnh. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Bangladesh.', '[\"/product/aophong/images/AP02_1.png\", \"/product/aophong/images/AP02_2.png\", \"/product/aophong/images/AP02_3.png\",\"/product/aophong/images/AP02_4.png\"]', '[\"AP03\", \"AP04\", \"AP05\"]', 429000, 0, '0.0'),
('/product/product.php?id=AP03', 'AP03', 'Áo phông', 'ÁO VẢI SẦN XẾP NẾP', 'Áo vải sần xếp nếp', '729.000 VND', 'Áo cổ tròn, dài tay. Khoét lưng. Gấu xếp nếp ở phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/aophong/images/AP03_1.png\", \"/product/aophong/images/AP03_2.png\", \"/product/aophong/images/AP03_3.png\",\"/product/aophong/images/AP03_4.png\"]', '[\"AP04\", \"AP05\", \"AP01\"]', 729000, 0, '0.0'),
('/product/product.php?id=AP04', 'AP04', 'Áo phông', 'ÁO PHÔNG HỌA TIẾT HELLO KITTY ©SANRIO\r\n', 'Áo phông họa tiết Hello Kitty ©Sanrio', '729.000 VND', 'Áo phông cổ tròn, dàI tay. Họa tiết Hello Kitty ©2021 Sanrio. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc.', '[\"/product/aophong/images/AP04_1.png\", \"/product/aophong/images/AP04_2.png\", \"/product/aophong/images/AP04_3.png\",\"/product/aophong/images/AP04_4.png\"]', '[\"AP05\", \"AP01\", \"AP02\"]', 729000, 0, '0.0'),
('/product/product.php?id=AP05', 'AP05', 'Áo phông', 'ÁO PHÔNG HỌA TIẾT CÔ GÁI\r\n', 'Áo phông họa tiết cô gái', '529.000 VND', 'Áo phông cổ tròn, cộc tay. Trang trí họa tiết khác màu. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/aophong/images/AP05_1.png\", \"/product/aophong/images/AP05_2.png\", \"/product/aophong/images/AP05_3.png\",\"/product/aophong/images/AP05_1.png\"]', '[\"AP01\", \"AP02\", \"AP03\"]', 529000, 0, '0.0'),
('/product/product.php?id=ASM01', 'ASM01', 'Áo sơ mi', 'ÁO SƠ MI IN HỌA TIẾT VÀ BUỘC DÂY\r\n', 'Áo sơ mi in họa tiết và buộc dây', '999.000 VND', 'Áo sơ mi vải rũ, cổ cao buộc dây. Xẻ chữ V trước ngực, dài tay.', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/aosomi/images/ASM01_1.png\", \"/product/aosomi/images/ASM01_2.png\", \"/product/aosomi/images/ASM01_3.png\",\"/product/aosomi/images/ASM01_4.png\"]', '[\"ASM02\", \"ASM03\", \"ASM04\"]', 999000, 0, '0.0'),
('/product/product.php?id=ASM02', 'ASM02', 'Áo sơ mi', 'ÁO SƠ MI KẺ CA RÔ VẢI RŨ\r\n', 'Áo sơ mi kẻ ca rô vải rũ', '999.000 VND', 'Áo sơ mi cổ cao, dài tay; có các chi tiết xếp nếp trang trí; xẻ và cài khuy sau cổ. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/aosomi/images/ASM02_1.png\", \"/product/aosomi/images/ASM02_2.png\", \"/product/aosomi/images/ASM02_3.png\",\"/product/aosomi/images/ASM02_4.png\"]', '[\"ASM03\", \"ASM04\", \"ASM05\"]', 999000, 1, '3.0'),
('/product/product.php?id=ASM03', 'ASM03', 'Áo sơ mi', 'ÁO SƠ MI VẢI GIẢ SA TANH CỔ CÓ DÂY BUỘC ', 'Áo sơ mi vải giả sa tanh cổ có dây buộc', '999.000 VND', 'Áo sơ mi cổ ve lật có dây buộc khác màu; dài tay; ráp bèo phía trước; cài khuy khảm đá trang sức phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Indonesia. ', '[\"/product/aosomi/images/ASM03_1.png\", \"/product/aosomi/images/ASM03_2.png\", \"/product/aosomi/images/ASM03_3.png\",\"/product/aosomi/images/ASM03_4.png\"]', '[\"ASM04\", \"ASM05\", \"ASM01\"]', 999000, 0, '0.0'),
('/product/product.php?id=ASM04', 'ASM04', 'Áo sơ mi', 'ÁO VẢI RŨ PHỐI VẢI DẬP LI\r\n', 'Áo vải rũ phối vải dập li', '999.000 VND', 'Áo cổ ráp bèo và có dây buộc. Dài tay, cổ tay cài khuy. Cài khuy màu vàng kim phía trước.', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Thổ Nhĩ Kỳ.', '[\"/product/aosomi/images/ASM04_1.png\", \"/product/aosomi/images/ASM04_2.png\", \"/product/aosomi/images/ASM04_3.png\",\"/product/aosomi/images/ASM04_4.png\"]', '[\"ASM05\", \"ASM01\", \"ASM02\"]', 999000, 1, '3.0'),
('/product/product.php?id=ASM05', 'ASM05', 'Áo sơ mi', 'ÁO SƠ MI POPLIN HỌA TIẾT HOA\r\n', 'Áo sơ mi Poplin họa tiết hoa', '799.000 VND', 'Áo sơ mi cổ ve lật, cộc tay; có hai túi đáp phía trước; cài khuy phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Thổ Nhĩ Kỳ. ', '[\"/product/aosomi/images/ASM05_1.png\", \"/product/aosomi/images/ASM05_2.png\", \"/product/aosomi/images/ASM05_3.png\",\"/product/aosomi/images/ASM05_4.png\"]', '[\"ASM01\", \"ASM02\", \"ASM03\"]', 799000, 0, '0.0'),
('/product/product.php?id=B01', 'B01', 'Blazer', 'ÁO KHOÁC BLAZER VẢI DỆT DÁNG NGẮN\r\n', 'Áo khoác blazer vải dệt dáng ngắn', '1.999.000 VND', 'Áo khoác blazer cổ tròn, dài tay; có hai túi giả có nắp và các chi tiết viền tua rua ở phía trước; cài khuy màu vàng kim khắc hoa văn nổi phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Việt Nam. ', '[\"/product/blazer/images/B01_1.png\", \"/product/blazer/images/B01_2.png\", \"/product/blazer/images/B01_3.png\",\"/product/blazer/images/B01_4.png\"]', '[\"B02\", \"B03\", \"B04\"]', 1999000, 0, '0.0'),
('/product/product.php?id=B02', 'B02', 'Blazer', 'ÁO KHOÁC BLAZER KẺ CA RÔ CHIẾT EO\r\n', 'Áo khoác blazer kẻ ca rô chiết eo', '2.299.000 VND', 'Áo khoác blazer cổ ve lật, dài tay, có đệm vai; có hai túi có nắp phía trước; cài khuy màu vàng kim khắc hoa văn nổi phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/blazer/images/B02_1.png\", \"/product/blazer/images/B02_2.png\", \"/product/blazer/images/B02_3.png\",\"/product/blazer/images/B02_4.png\"]', '[\"B03\", \"B04\", \"B05\"]', 2299000, 0, '0.0'),
('/product/product.php?id=B03', 'B03', 'Blazer', 'ÁO KHOÁC BLAZER DÁNG DÀI CÓ VẠT ĐẮP CHÉO ', 'Áo khoác blazer dáng dài có vạt đắp chéo', '2.299.000 VND', 'Blazer vừa vặn có vạt cổ áo, tay dài, vai vừa vặn; túi trước lật được, trước ngực có nút cài kim loại. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/blazer/images/B03_1.png\", \"/product/blazer/images/B03_2.png\", \"/product/blazer/images/B03_3.png\",\"/product/blazer/images/B03_4.png\"]', '[\"B04\", \"B05\", \"B01\"]', 2299000, 0, '0.0'),
('/product/product.php?id=B04', 'B04', 'Blazer', 'ÁO TUXEDO DÁNG BLAZER\r\n', 'Áo tuxedo dáng blazer', '1.999.000 VND', 'Áo khoác blazer cổ ve lật bằng vải sa tanh, dài tay, có đệm vai; có hai túi có nắp phía trước; có một khuy cài bọc vải cùng màu phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/blazer/images/B04_1.png\", \"/product/blazer/images/B04_2.png\", \"/product/blazer/images/B04_3.png\",\"/product/blazer/images/B04_4.png\"]', '[\"B05\", \"B01\", \"B02\"]', 1999000, 0, '0.0'),
('/product/product.php?id=B05', 'B05', 'Blazer', 'ÁO KHOÁC BLAZER OVERSIZE HỌA TIẾT HOUNDSTOOTH\r\n', 'Áo khoác blazer oversize họa tiết houndstooth', '1.999.000 VND', 'Áo khoác blazer cổ ve lật, dài tay, có đệm vai; có hai túi có nắp phía trước; cài khuy phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Trung Quốc. ', '[\"/product/blazer/images/B05_1.png\", \"/product/blazer/images/B05_2.png\", \"/product/blazer/images/B05_3.png\",\"/product/blazer/images/B05_4.png\"]', '[\"B01\", \"B02\", \"B03\"]', 1999000, 0, '0.0'),
('/product/product.php?id=CL01', 'CL01', 'Com lê', 'ÁO KHOÁC BLAZER CHIẾT EO VẠT ĐẮP CHÉO\r\n', 'Áo khoác blazer chiết eo vạt đắp chéo', '1.999.000 VND ', 'Áo khoác blazer cổ ve lật, dài tay, có đệm vai; có hai túi có nắp phía trước; gấu xẻ phía sau; có vạt đắp chéo, cài khuy kim loại phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/comle/images/CL01_1.png\", \"/product/comle/images/CL01_2.png\", \"/product/comle/images/CL01_3.png\",\"/product/comle/images/CL01_4.png\"]', '[\"CL02\", \"CL03\", \"CL04\"]', 1999000, 0, '0.0'),
('/product/product.php?id=CL02', 'CL02', 'Com lê', 'ÁO KHOÁC BLAZER CHIẾT EO VẠT ĐẮP CHÉO', 'Áo khoác blazer chiết eo vạt đắp chéo ', '1.999.000 VND ', 'Áo khoác blazer cổ ve lật, dài tay, có đệm vai; có hai túi có nắp phía trước; gấu xẻ phía sau; có vạt đắp chéo, cài khuy kim loại phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/comle/images/CL02_1.png\", \"/product/comle/images/CL02_2.png\", \"/product/comle/images/CL02_3.png\",\"/product/comle/images/CL02_4.png\"]', '[\"CL03\", \"Cl04\", \"CL05\"]', 1999000, 0, '0.0'),
('/product/product.php?id=CL03', 'CL03', 'Com lê', 'ÁO KHOÁC BLAZER CHIẾT EO VẠT ĐẮP CHÉO ', 'Áo khoác blazer chiết eo vạt đắp chéo ', '1.999.000 VND ', 'Áo khoác blazer cổ ve lật, dài tay, có đệm vai; có hai túi có nắp phía trước; gấu xẻ phía sau; có vạt đắp chéo, cài khuy kim loại phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/comle/images/CL03_1.png\", \"/product/comle/images/CL03_2.png\", \"/product/comle/images/CL03_3.png\",\"/product/comle/images/CL03_4.png\"]', '[\"CL04\", \"Cl05\", \"CL01\"]', 1999000, 0, '0.0'),
('/product/product.php?id=CL04', 'CL04', 'Com lê', 'ÁO KHOÁC BLAZER CHIẾT EO VẠT ĐẮP CHÉO\r\n', 'Áo khoác blazer chiết eo vạt đắp chéo ', '1.999.000 VND ', 'Áo khoác blazer cổ ve lật, dài tay, có đệm vai; có hai túi có nắp phía trước; gấu xẻ phía sau; có vạt đắp chéo, cài khuy kim loại phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/comle/images/CL04_1.png\", \"/product/comle/images/CL04_2.png\", \"/product/comle/images/CL04_3.png\",\"/product/comle/images/CL04_4.png\"]', '[\"CL05\", \"Cl01\", \"CL02\"]', 1999000, 0, '0.0'),
('/product/product.php?id=CL05', 'CL05', 'Com lê', 'ÁO KHOÁC BLAZER CHIẾT EO VẠT ĐẮP CHÉO ', 'Áo khoác blazer chiết eo vạt đắp chéo ', '1.999.000 VND ', 'Áo khoác blazer cổ ve lật, dài tay, có đệm vai; có hai túi có nắp phía trước; gấu xẻ phía sau; có vạt đắp chéo, cài khuy kim loại phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/comle/images/CL05_1.png\", \"/product/comle/images/CL05_2.png\", \"/product/comle/images/CL05_3.png\",\"/product/comle/images/CL05_4.png\"]', '[\"CL01\", \"Cl02\", \"CL03\"]', 1999000, 0, '0.0'),
('/product/product.php?id=D01', 'D01', 'Đầm', 'ĐẦM MINI KHOÉT TẠO KIỂU\r\n', 'Đầm mini khoét tạo kiểu ', '1.299.000 VND ', 'Đầm cổ chữ v, vạt đắp chéo, có hai dây đeo vai mảnh; xếp nếp trang trí, khoét bụng phía trước; cài bằng khóa kéo ẩn ở đường may sau lưng. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Thổ Nhĩ Kỳ. ', '[\"/product/dam/images/D01_1.png\", \"/product/dam/images/D01_2.png\", \"/product/dam/images/D01_3.png\",\"/product/aopdamhong/images/D01_4.png\"]', '[\"D02\", \"D03\", \"D04\"]', 1299000, 0, '0.0'),
('/product/product.php?id=D02', 'D02', 'Đầm', 'ĐẦM NHUNG PHIÊN BẢN GIỚI HẠN ', 'Đầm nhung phiên bản giới hạn ', '1.999.000 VND ', 'Đầm ngắn cổ ngang, khoét trước ngực, có dây đeo cổ cùng chất liệu; nhún li và xếp nếp co giãn kiểu tổ ong ở hai bên. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Maroc. ', '[\"/product/dam/images/D02_1.png\", \"/product/dam/images/D02_2.png\", \"/product/dam/images/D02_3.png\",\"/product/aopdamhong/images/D02_4.png\"]', '[\"D03\", \"D04\", \"D05\"]', 1999000, 0, '0.0'),
('/product/product.php?id=D03', 'D03', 'Đầm', 'ĐẦM DỆT KIM CỔ TRỤ ', 'Đầm dệt kim cổ trụ ', '999.000 VND ', 'Đầm ngắn cổ ngang, khoét trước ngực, có dây đeo cổ cùng chất liệu; nhún li và xếp nếp co giãn kiểu tổ ong ở hai bên. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Bangladesh. ', '[\"/product/dam/images/D03_1.png\", \"/product/dam/images/D03_2.png\", \"/product/dam/images/D03_3.png\",\"/product/aopdamhong/images/D03_4.png\"]', '[\"D04\", \"D05\", \"D01\"]', 999000, 0, '0.0'),
('/product/product.php?id=D04', 'D04', 'Đầm', 'ĐẦM NHUNG NHÚN LI ', 'Đầm nhung nhún li ', '1.299.000 VND ', 'Đầm ngắn cổ ngang, khoét trước ngực, có dây đeo cổ cùng chất liệu; nhún li và xếp nếp co giãn kiểu tổ ong ở hai bên. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Trung Quốc. ', '[\"/product/dam/images/D04_1.png\", \"/product/dam/images/D04_2.png\", \"/product/dam/images/D04_3.png\",\"/product/aopdamhong/images/D04_4.png\"]', '[\"D05\", \"D01\", \"D02\"]', 1299000, 0, '0.0'),
('/product/product.php?id=D05', 'D05', 'Đầm', 'ĐẦM NHUNG IN HỌA TIẾT ', 'Đầm nhung in họa tiết ', '1.299.000 VND ', 'Đầm ngắn cổ ve lật, dài tay, cổ tay bo thun co giãn; kèm thắt lưng cùng chất liệu; cài khuy phía trước. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Trung Quốc. ', '[\"/product/dam/images/D05_1.png\", \"/product/dam/images/D05_2.png\", \"/product/dam/images/D05_3.png\",\"/product/aopdamhong/images/D05_4.png\"]', '[\"D01\", \"D02\", \"D03\"]', 1299000, 0, '0.0'),
('/product/product.php?id=G01', 'G01', 'Giày', 'BỐT GIẢ DA BÓNG CỔ CAO ', 'Bốt giả da bóng cổ cao ', '2.299.000 VND ', 'Bốt cổ cao. ống bốt giả da bóng, co giãn. đế dày, có rãnh răng cưa. cài khóa kéo ở mặt phía bên trong. mũi vuông. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường\r\n        <br>\r\n        - Những thao tác đơn giản như lau chùi sản phẩm bằng khăn bông khô hoặc bàn chải mềm, tùy thuộc vào đặc tính của sản phẩm, cũng có thể giúp chúng ta chăm sóc chúng. Bất cứ khi nào có thể, hãy cố gắng sử dụng các sản phẩm thân thiện với môi trường.\r\n        <br>\r\n        - Không giặt\r\n        <br>\r\n        - Không nhúng nước\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy\r\n        <br>\r\n        - Da thuộc/Da bóng/Da trơn. Lau sạch bằng khăn bông khô.\r\n        <br>\r\n        - Không là\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Làm sạch bằng bàn chải mềm hoặc miếng bọt biển cứng. \r\n        <br>\r\n        - Không giặt khô\r\n        <br>\r\n        - Da thuộc. Có thể sử dụng các loại sáp không màu hoặc có tông màu da.\r\n        <br>\r\n        - Không sử dụng máy sấy\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Có thể bảo vệ bằng cách sử dụng các chai xịt xử lý hoặc chống bám bụi (như chai xịt chống thấm nước cho cây lau nhà).', 'Sản xuất tại Trung Quốc.\r\n', '[\"/product/giay/images/G01_1.png\", \"/product/giay/images/G01_2.png\", \"/product/giay/images/G01_3.png\",\"/product/giay/images/G01_1.png\"]', '[\"G02\", \"G03\", \"G04\"]', 2299000, 0, '0.0'),
('/product/product.php?id=G02', 'G02', 'Giày', 'BỐT DA CỔ NGẮN CAO GÓT ', 'Bốt da cổ ngắn cao gót ', '2.299.000 VND ', 'Bốt da cổ ngắn, có gót nhọn. mũi nhọn. cài khóa kéo ở mặt phía bên trong. gót cao, mảnh. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường\r\n        <br>\r\n        - Những thao tác đơn giản như lau chùi sản phẩm bằng khăn bông khô hoặc bàn chải mềm, tùy thuộc vào đặc tính của sản phẩm, cũng có thể giúp chúng ta chăm sóc chúng. Bất cứ khi nào có thể, hãy cố gắng sử dụng các sản phẩm thân thiện với môi trường.\r\n        <br>\r\n        - Không giặt\r\n        <br>\r\n        - Không nhúng nước\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy\r\n        <br>\r\n        - Da thuộc/Da bóng/Da trơn. Lau sạch bằng khăn bông khô.\r\n        <br>\r\n        - Không là\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Làm sạch bằng bàn chải mềm hoặc miếng bọt biển cứng. \r\n        <br>\r\n        - Không giặt khô\r\n        <br>\r\n        - Da thuộc. Có thể sử dụng các loại sáp không màu hoặc có tông màu da.\r\n        <br>\r\n        - Không sử dụng máy sấy\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Có thể bảo vệ bằng cách sử dụng các chai xịt xử lý hoặc chống bám bụi (như chai xịt chống thấm nước cho cây lau nhà).', 'Sản xuất tại Campuchia. ', '[\"/product/giay/images/G02_1.png\", \"/product/giay/images/G02_2.png\", \"/product/giay/images/G02_3.png\",\"/product/giay/images/G02_1.png\"]', '[\"G03\", \"G04\", \"G05\"]', 2299000, 0, '0.0'),
('/product/product.php?id=G03', 'G03', 'Giày', 'BỐT DA BUỘC DÂY ĐẾ RĂNG CƯA ', 'Bốt da buộc dây đế răng cưa ', '4.599.000 VND ', 'Bốt da màu đen. cài khóa kéo ở mặt phía bên trong, có dây buộc ở phía trước. đế dày, có rãnh răng cưa. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường\r\n        <br>\r\n        - Những thao tác đơn giản như lau chùi sản phẩm bằng khăn bông khô hoặc bàn chải mềm, tùy thuộc vào đặc tính của sản phẩm, cũng có thể giúp chúng ta chăm sóc chúng. Bất cứ khi nào có thể, hãy cố gắng sử dụng các sản phẩm thân thiện với môi trường.\r\n        <br>\r\n        - Không giặt\r\n        <br>\r\n        - Không nhúng nước\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy\r\n        <br>\r\n        - Da thuộc/Da bóng/Da trơn. Lau sạch bằng khăn bông khô.\r\n        <br>\r\n        - Không là\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Làm sạch bằng bàn chải mềm hoặc miếng bọt biển cứng. \r\n        <br>\r\n        - Không giặt khô\r\n        <br>\r\n        - Da thuộc. Có thể sử dụng các loại sáp không màu hoặc có tông màu da.\r\n        <br>\r\n        - Không sử dụng máy sấy\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Có thể bảo vệ bằng cách sử dụng các chai xịt xử lý hoặc chống bám bụi (như chai xịt chống thấm nước cho cây lau nhà).', 'Sản xuất tại Campuchia. ', '[\"/product/giay/images/G03_1.png\", \"/product/giay/images/G03_2.png\", \"/product/giay/images/G03_3.png\",\"/product/giay/images/G03_1.png\"]', '[\"G04\", \"G05\", \"G01\"]', 4599000, 0, '0.0'),
('/product/product.php?id=G04', 'G04', 'Giày', 'GIÀY THỂ THAO ĐẾ RĂNG CƯA', 'Giày thể thao đế răng cưa ', '1.799.000 VND ', 'Giày thể thao leo núi bằng da. có các quai hỗ trợ xỏ giày ở lưỡi gà và phía sau. đế dày, phối nhiều màu, có rãnh răng cưa. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường\r\n        <br>\r\n        - Những thao tác đơn giản như lau chùi sản phẩm bằng khăn bông khô hoặc bàn chải mềm, tùy thuộc vào đặc tính của sản phẩm, cũng có thể giúp chúng ta chăm sóc chúng. Bất cứ khi nào có thể, hãy cố gắng sử dụng các sản phẩm thân thiện với môi trường.\r\n        <br>\r\n        - Không giặt\r\n        <br>\r\n        - Không nhúng nước\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy\r\n        <br>\r\n        - Da thuộc/Da bóng/Da trơn. Lau sạch bằng khăn bông khô.\r\n        <br>\r\n        - Không là\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Làm sạch bằng bàn chải mềm hoặc miếng bọt biển cứng. \r\n        <br>\r\n        - Không giặt khô\r\n        <br>\r\n        - Da thuộc. Có thể sử dụng các loại sáp không màu hoặc có tông màu da.\r\n        <br>\r\n        - Không sử dụng máy sấy\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Có thể bảo vệ bằng cách sử dụng các chai xịt xử lý hoặc chống bám bụi (như chai xịt chống thấm nước cho cây lau nhà).', 'Sản xuất tại Trung Quốc. ', '[\"/product/giay/images/G04_1.png\", \"/product/giay/images/G04_2.png\", \"/product/giay/images/G04_3.png\",\"/product/giay/images/G04_1.png\"]', '[\"G05\", \"G01\", \"G02\"]', 1799000, 0, '0.0'),
('/product/product.php?id=G05', 'G05', 'Giày', 'BỐT DA ĐẾ RĂNG CƯA ', 'Bốt da đế răng cưa ', '2.699.000 VND ', 'Bốt da cổ ngắn đế bằng. phối đai co giãn ở hai bên. có quai hỗ trợ xỏ ở phía trước và phía sau. đế có rãnh răng cưa. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường\r\n        <br>\r\n        - Những thao tác đơn giản như lau chùi sản phẩm bằng khăn bông khô hoặc bàn chải mềm, tùy thuộc vào đặc tính của sản phẩm, cũng có thể giúp chúng ta chăm sóc chúng. Bất cứ khi nào có thể, hãy cố gắng sử dụng các sản phẩm thân thiện với môi trường.\r\n        <br>\r\n        - Không giặt\r\n        <br>\r\n        - Không nhúng nước\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy\r\n        <br>\r\n        - Da thuộc/Da bóng/Da trơn. Lau sạch bằng khăn bông khô.\r\n        <br>\r\n        - Không là\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Làm sạch bằng bàn chải mềm hoặc miếng bọt biển cứng. \r\n        <br>\r\n        - Không giặt khô\r\n        <br>\r\n        - Da thuộc. Có thể sử dụng các loại sáp không màu hoặc có tông màu da.\r\n        <br>\r\n        - Không sử dụng máy sấy\r\n        <br>\r\n        - Da lộn/Da Nubuck/Da mài. Có thể bảo vệ bằng cách sử dụng các chai xịt xử lý hoặc chống bám bụi (như chai xịt chống thấm nước cho cây lau nhà).', 'Sản xuất tại Trung Quốc. ', '[\"/product/giay/images/G05_1.png\", \"/product/giay/images/G05_2.png\", \"/product/giay/images/G05_3.png\",\"/product/giay/images/G05_1.png\"]', '[\"G01\", \"G02\", \"G03\"]', 2699000, 0, '0.0'),
('/product/product.php?id=K01', 'K01', 'Áo khoác', 'ÁO KHOÁC PHA LEN CÓ VẠT ĐẮP CHÉO', 'Áo khoác pha len có vạt đắp chéo', '3.999.000 VND', 'Áo khoác dài may chiết eo, chất liệu pha len. cổ ve lật, dài tay; có hai túi có nắp phía trước; gấu xẻ phía sau; vạt đắp chéo, cài khuy phía trước.', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.', 'Sản xuất tại Maroc.\r\n', '[\"/product/aokhoac/images/K01_1.JPG\", \"/product/aokhoac/images/K01_2.JPG\", \"/product/aokhoac/images/K01_3.JPG\",\"/product/aokhoac/images/K01_4.JPG\"]', '[\"K02\", \"K03\", \"K04\"]', 3999000, 0, '0.0'),
('/product/product.php?id=K02', 'K02', 'Áo khoác', 'ÁO KHOÁC PHA LEN CÓ VẠT ĐẮP CHÉO', 'Áo khoác dài pha len cổ đắp chéo', '3.499.000 VND', 'Áo khoác dáng dài, cổ ve lật bản to, dài tay; có hai túi may viền phía trước; cài phía trước bằng khuy bấm ẩn.', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.', 'Sản xuất tại Trung Quốc.', '[\"/product/aokhoac/images/K02_1.JPG\", \"/product/aokhoac/images/K02_2.JPG\", \"/product/aokhoac/images/K02_3.JPG\",\"/product/aokhoac/images/K02_4.JPG\"]', '[\"K01\", \"K03\", \"K04\"]', 3499000, 0, '0.0'),
('/product/product.php?id=K03', 'K03', 'Áo khoác', 'ÁO KHOÁC DÀI PHỐI VẢI DÁNG ÁO BOMBER', 'Áo khoác dài phối vải dáng áo Bomber', '3.499.000 VND', 'Áo khoác dài dáng áo bomber, chất liệu pha len, cổ ve lật; tay dài cùng màu, bo cổ tay; có hai túi phía trước và một túi đáp ở một bên tay áo; kèm thắt lưng cùng chất liệu; bên trong lót vải khác màu.', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.', 'Sản xuất tại Maroc.', '[\"/product/aokhoac/images/K03_1.JPG\", \"/product/aokhoac/images/K03_2.JPG\", \"/product/aokhoac/images/K03_3.JPG\",\"/product/aokhoac/images/K03_4.JPG\"]', '[\"K01\", \"K02\", \"K04\"]', 3499000, 0, '0.0'),
('/product/product.php?id=K04', 'K04', 'Áo khoác', 'ÁO KHOÁC DÀI PHỐI VẢI DÁNG ÁO BOMBER', 'Áo khoác dài phối vải dáng áo Bomber', '3.499.000 VND', 'Áo khoác dài dáng áo bomber, chất liệu pha len, cổ ve lật; tay dài cùng màu, bo cổ tay; có hai túi phía trước và một túi đáp ở một bên tay áo; kèm thắt lưng cùng chất liệu; bên trong lót vải khác màu.', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.', 'Sản xuất tại Maroc.', '[\"/product/aokhoac/images/K04_1.JPG\", \"/product/aokhoac/images/K04_2.JPG\", \"/product/aokhoac/images/K04_3.JPG\",\"/product/aokhoac/images/K04_4.JPG\"]', '[\"K01\", \"K02\", \"K03\"]', 3499000, 0, '0.0'),
('/product/product.php?id=Q01', 'Q01', 'Quần', 'QUẦN CẠP CAO\r\n', 'Quần cạp cao ', '999.000 VND ', 'Quần cạp cao, có các đường may nổi ở phía trước và phía sau; có hai túi may viền phía trước; cài phía trước bằng khóa kéo, khuy ẩn và móc kim loại. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Trung Quốc. ', '[\"/product/quan/images/Q01_1.png\", \"/product/quan/images/Q01_2.png\", \"/product/quan/images/Q01_3.png\",\"/product/quan/images/Q01_4.png\"]', '[\"Q02\", \"Q03\", \"Q04\"]', 999000, 0, '0.0'),
('/product/product.php?id=Q02', 'Q02', 'Quần', 'QUẦN PAPER BAG CẠP CO GIÃN ', 'Quần paper bag cạp co giãn ', '999.000 VND ', 'Quần cạp cao, có các đường may nổi ở phía trước và phía sau; có hai túi may viền phía trước; cài phía trước bằng khóa kéo, khuy ẩn và móc kim loại. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Campuchia. ', '[\"/product/quan/images/Q02_1.png\", \"/product/quan/images/Q02_2.png\", \"/product/quan/images/Q02_3.png\",\"/product/quan/images/Q02_4.png\"]', '[\"Q03\", \"Q04\", \"Q05\"]', 999000, 0, '0.0'),
('/product/product.php?id=Q03', 'Q03', 'Quần', 'QUẦN CHINO ', 'Quần chino ', '999.000 VND ', 'Quần cạp cao, có các đường may nổi ở phía trước và phía sau; có hai túi may viền phía trước; cài phía trước bằng khóa kéo, khuy ẩn và móc kim loại. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Tây Ban Nha.\r\n', '[\"/product/quan/images/Q03_1.png\", \"/product/quan/images/Q03_2.png\", \"/product/quan/images/Q03_3.png\",\"/product/quan/images/Q03_4.png\"]', '[\"Q04\", \"Q05\", \"Q01\"]', 999000, 0, '0.0'),
('/product/product.php?id=Q04', 'Q04', 'Quần', 'QUẦN PLEATED ', 'Quần pleated ', '999.000 VND', 'Quần áo cao cấp có ổ cắm bên mặt và ổ cắm bay ảnh thật sai lầm. nổi bật chi tiết trên thông số, xem chi tiết trên biết, bảng điều chỉnh trên móc hem và móc kim loại, nút bên trong và móc zip nhanh ở phía trước.', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Myanmar. ', '[\"/product/quan/images/Q04_1.png\", \"/product/quan/images/Q04_2.png\", \"/product/quan/images/Q04_3.png\",\"/product/quan/images/Q04_4.png\"]', '[\"Q05\", \"Q01\", \"Q02\"]', 999000, 0, '0.0'),
('/product/product.php?id=Q05', 'Q05', 'Quần', 'QUẦN CẠP CAO ', 'Quần cạp cao ', '999.000 VND', 'Quần cạp cao, có các đường may nổi phía trước. có hai túi thật may viền phía trước và một túi giả may viền phía sau. cài phía trước bằng khóa kéo, khuy ẩn và móc kim loại. ', '        <br>\r\n        - Chăm sóc đúng cách quần áo của mình tức là bạn đang bảo vệ môi trường.\r\n        <br>\r\n        - Để giữ cho áo khoác của bạn sạch sẽ, bạn chỉ cần phơi chúng ở nơi thông thoáng và lau sạch bằng khăn vải hoặc bàn chải chuyên dụng. Nếu cần thiết phải giặt khô, hãy cố gắng tìm những tiệm giặt ủi sử dụng các công nghệ thân thiện với môi trường.\r\n        <br>\r\n        - Không sử dụng nước tẩy / thuốc tẩy.\r\n        <br>\r\n        - Giặt ở nhiệt độ tối đa 110ºC.\r\n        <br>\r\n        - Giặt khô với tetrachloroethylene.\r\n        <br>\r\n        - Không sử dụng máy sấy.\r\n        <br>\r\n        - Giặt riêng.', 'Sản xuất tại Thổ Nhĩ Kỳ. ', '[\"/product/quan/images/Q05_1.png\", \"/product/quan/images/Q05_2.png\", \"/product/quan/images/Q05_3.png\",\"/product/quan/images/Q05_4.png\"]', '[\"Q01\", \"Q02\", \"Q03\"]', 999000, 0, '0.0');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `userdb`
--

CREATE TABLE `userdb` (
  `id` int(11) NOT NULL,
  `uname` varchar(40) DEFAULT NULL,
  `pword` varchar(50) DEFAULT NULL,
  `privilege` varchar(15) CHARACTER SET ascii DEFAULT NULL,
  `ubalance` int(255) DEFAULT 0,
  `cart` varchar(1000) CHARACTER SET utf32 DEFAULT '[]'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Đang đổ dữ liệu cho bảng `userdb`
--

INSERT INTO `userdb` (`id`, `uname`, `pword`, `privilege`, `ubalance`, `cart`) VALUES
(0, 'long014756', '123456', 'user', 201000, '[\"ASM04\",\"K01\",\"G02\",\"ASM01\",\"ASM02\",\"ASM05\"]'),
(1, 'long', 'long014756', 'admin', 0, '[\"K02\",\"ASM02\",\"ASM05\"]'),
(2, 'mp5navy', '123456', 'user', 0, '[\"AP04\",\"AP05\"]'),
(3, 'tester', 'test', 'user', 800123, '[\"K02\",\"ASM03\",\"ASM01\",\"D02\",\"D03\"]'),
(4, 'test', '123456', 'user', 7998000, '[\"AP02\",\"K01\",\"K02\",\"K03\"]'),
(5, 'longs', 'longs', 'user', 0, '[]'),
(6, 'tester2', '123456', 'user', 0, '[]'),
(7, 'testno3', '014756', 'user', 0, '[]');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `comment`
--
ALTER TABLE `comment`
  ADD PRIMARY KEY (`comment_id`);

--
-- Chỉ mục cho bảng `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`order_id`);

--
-- Chỉ mục cho bảng `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`product_code`);

--
-- Chỉ mục cho bảng `userdb`
--
ALTER TABLE `userdb`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`),
  ADD UNIQUE KEY `uname` (`uname`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `comment`
--
ALTER TABLE `comment`
  MODIFY `comment_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
